# Generated by Django 4.2.6 on 2023-10-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='user', max_length=64),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
